definitions:
  models.Event:
    properties:
      date:
        type: string
      description:
        minLength: 10
        type: string
      id:
        type: integer
      location:
        minLength: 3
        type: string
      name:
        minLength: 3
        type: string
      owner_id:
        type: integer
    required:
    - date
    - description
    - location
    - name
    type: object
info:
  contact: {}
  description: Enter your bearer token in the format **Bearer &lt;token&gt;**
  title: Go Gin Rest API
  version: 1.0.0
paths:
  /api/v1/events:
    get:
      consumes:
      - application/json
      description: Returns all events
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Event'
            type: array
      summary: Returns all events
      tags:
      - Events
swagger: "2.0"
